# configs/evaluate.yaml

seed: 42
device: cuda

model:
  _target_: nets.MLPClassifier
  hidden_size: 512
  input_size: 256
  num_classes: 4

training:
  num_epochs: 100
  batch_size: 512
  num_workers: 4
  early_stopping: 20  # Stop if no improvement for 10 epochs
  optimizer:
    lr: 0.01

output:
  results_path: 'results'
  exp_name: 'compare_batch_size'
  run_name: 'batch_size=8'

data:
  train_embeddings_path: ${output.results_path}/${output.exp_name}/${output.run_name}/inference_results/train_embeds.parquet
  test_embeddings_path: ${output.results_path}/${output.exp_name}/${output.run_name}/inference_results/test_embeds.parquet
  val_size: 0.1  # Split 10% of train for validation